name: task_hyd
description: "The Bhasausa.tech task from HYD."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  auto_route: ^8.0.3
  velocity_x: ^4.1.2
  video_player: ^2.8.6
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
